[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_address_lookup_table_example = "ALT4bMa1vKx8fAEbrTYFE1cx86HyKV49LpaNHMBcQZTJ"

[programs.devnet]
anchor_address_lookup_table_example = "ALT4bMa1vKx8fAEbrTYFE1cx86HyKV49LpaNHMBcQZTJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
